config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new', as: 'signup'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users

  resources :microposts,          only: [:create, :destroy]



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord

  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }

end

app/models/user.rb
class User < ApplicationRecord

  has_many :entries, dependent: :destroy

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Create password for user fixture testing

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :     BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :fetch_user

  include SessionsHelper

private

  def fetch_user

    if session[:user_id].present?
      @current_user = User.find_by :id => session[:user_id]


      session[:user_id] = nil unless @current_user
    end
  end

  def authorize_user
   redirect_to root_path unless @current_user.present?
  end

  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_action :logged_in_user, only: [:create, :destroy]

  def create
  end

  def destroy
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end

  def help

  end

  def contact

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :authorize_user, :except => [:new, :create]

  def show
   @user = User.find(params[:id])
   @entries = @user.entries.paginate(page: params[:page])
  end

  def new
   @user = User.new
  end

  def create
   @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to My Journal"
      redirect_to @user
    else
      render 'new'
    end
  end



  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
   session[:user_id] = user.id
 end

 def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/entries/_entry.html.erb
<li id="entry-<%= entry.id %>">
  <!-- Will need to look at the CSS later -->

  <span class="user"><%= link_to entry.user.name, entry.user %></span>
  <span class="content"><%= entry.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(entry.created_at) %> ago.
  </span>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyJournal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
       <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>


     <!--  This can go into a file _header.html.erb  -->
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>

     <% if logged_in? %>
      <ul>
        <li><%= link_to "Users", '#' %></li>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", '#' %></li>
        <li><%= link_to "Log out", logout_path, method: :delete %></li>
      </ul>
     <% else %>
          <ul>
            <li><%= link_to "Log in", login_path %></li>
          </ul>
     <% end %>

     <!--  -->

    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<h1>You are at the contact page</h1>

app/views/static_pages/help.html.erb
<h1>You are at the help page</h1>

app/views/static_pages/home.html.erb
<h1>You are at the home page</h1>


<div id="just_for_today">

<h3>Just for today</h3>

<p>Just for today I will try and live through this day only, and not tackle my whole life problem at once. I can do something for twelve hours that would appal me if I felt that I had to keep it up for a lifetime.</p>

<p>Just for today I will be happy. Most folks are as happy as they make up their minds to be.</p>

<p>Just for today I will adjust myself to what is, and not try to adjust everything to my own desires. I will take my 'luck' as it comes, and fit myself to it.</p>

<p>Just for today I will try to strengthen my mind. I will study. I will learn something useful. I will not be a mental loafer. I will read something that requries effort, thought and concentration.</p>

<p>Just for today I will excercise my soul in three ways: I will do somebody a good turn, and not get found out; if anybody knows of it, it will not count. I will do at least two things I don't want to do - just for exercise. I will not show anyone that my feelings are hurt; they may be hurt, but today I will not show it.</p>

<p>Just for today I wil be agreeable. I will look as well as I can, dress becomingly, talk low, act courteously, criticise not one bit, not find fault with anything and not try to improve or regulate anybody except myself.</p>

<p>Just for today I will have a programme. I may not follow it exactly, but I will have it. I will save myself from tow pests: hurry and indecision.</p>

<p>Just for today I will have a quiet half hour all by myself, and relax. During this half hour, something, I will try to get a better perspective of my life.</p>

<p>Just for today I will be unafraid. Especially I will not be afraid to enjoy what is beautiful, and to believe that as I give to the world, so the world will give to me.</p>

</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div>
    <%= form_for(@user) do |f| %>

    <%= render 'shared/error_messages' %>
    
    <fieldset>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </fieldset>
    <fieldset>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </fieldset>
    <fieldset>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </fieldset>
    <fieldset>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
    </fieldset>
      <%= f.submit "Create my account" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= Time.now %>
<p><%= @user.name %>, <%= @user.email %></p>

<div>
  <% if @user.entries.any? %>
    <h3>Entries (<%= @user.entries.count %>)</h3>
    <ol >
      <%= render @entries %>
    </ol>
    <%= will_paginate @entries %>
  <% end %>
</div>